### ISSUE TITLE
Exceptions in the browser console

### ISSUE THREAD

**Issue by Antonytm** [contentful/contentful-graphql-playground-app#10]
GraphQL Playground does not start. I get these exception in the browser console:

```
osano.js:2 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.
l @ osano.js:2
value @ osano.js:2
M @ vendors~app-f22ca52aac3beedfa19a.js:702
rs @ vendors~app-f22ca52aac3beedfa19a.js:702
wc @ vendors~app-f22ca52aac3beedfa19a.js:702
zc @ vendors~app-f22ca52aac3beedfa19a.js:702
Ac @ vendors~app-f22ca52aac3beedfa19a.js:702
Ec @ vendors~app-f22ca52aac3beedfa19a.js:702
mc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
Hi @ vendors~app-f22ca52aac3beedfa19a.js:702
Ui @ vendors~app-f22ca52aac3beedfa19a.js:702
uc @ vendors~app-f22ca52aac3beedfa19a.js:702
za @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ app-6837daecd574fbdaf57f.js:1
await in (anonymous) (async)
(anonymous) @ app-6837daecd574fbdaf57f.js:1
Rc @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
kc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
L @ vendors~app-f22ca52aac3beedfa19a.js:702
M.port1.onmessage @ vendors~app-f22ca52aac3beedfa19a.js:702
osano.js:2 Allow attribute will take precedence over 'allowfullscreen'.
l @ osano.js:2
value @ osano.js:2
M @ vendors~app-f22ca52aac3beedfa19a.js:702
rs @ vendors~app-f22ca52aac3beedfa19a.js:702
wc @ vendors~app-f22ca52aac3beedfa19a.js:702
zc @ vendors~app-f22ca52aac3beedfa19a.js:702
Ac @ vendors~app-f22ca52aac3beedfa19a.js:702
Ec @ vendors~app-f22ca52aac3beedfa19a.js:702
mc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
Hi @ vendors~app-f22ca52aac3beedfa19a.js:702
Ui @ vendors~app-f22ca52aac3beedfa19a.js:702
uc @ vendors~app-f22ca52aac3beedfa19a.js:702
za @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ app-6837daecd574fbdaf57f.js:1
await in (anonymous) (async)
(anonymous) @ app-6837daecd574fbdaf57f.js:1
Rc @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
kc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
L @ vendors~app-f22ca52aac3beedfa19a.js:702
M.port1.onmessage @ vendors~app-f22ca52aac3beedfa19a.js:702
osano.js:2 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
value @ osano.js:2
Ms @ vendors~app-f22ca52aac3beedfa19a.js:702
Ms @ vendors~app-f22ca52aac3beedfa19a.js:702
Ms @ vendors~app-f22ca52aac3beedfa19a.js:702
Ms @ vendors~app-f22ca52aac3beedfa19a.js:702
Ms @ vendors~app-f22ca52aac3beedfa19a.js:702
ys @ vendors~app-f22ca52aac3beedfa19a.js:702
Cc @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
Tc @ vendors~app-f22ca52aac3beedfa19a.js:702
mc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
Hi @ vendors~app-f22ca52aac3beedfa19a.js:702
Ui @ vendors~app-f22ca52aac3beedfa19a.js:702
uc @ vendors~app-f22ca52aac3beedfa19a.js:702
za @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ app-6837daecd574fbdaf57f.js:1
await in (anonymous) (async)
(anonymous) @ app-6837daecd574fbdaf57f.js:1
Rc @ vendors~app-f22ca52aac3beedfa19a.js:702
t.unstable_runWithPriority @ vendors~app-f22ca52aac3beedfa19a.js:702
Wi @ vendors~app-f22ca52aac3beedfa19a.js:702
kc @ vendors~app-f22ca52aac3beedfa19a.js:702
(anonymous) @ vendors~app-f22ca52aac3beedfa19a.js:702
L @ vendors~app-f22ca52aac3beedfa19a.js:702
M.port1.onmessage @ vendors~app-f22ca52aac3beedfa19a.js:702
2vendors~app-f22ca52aac3beedfa19a.js:2 Wootric: Warning: Invalid created_at, expecting 10-digit Unix timestamp in seconds.
2.987ef8f6.chunk.js:2 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at n.mapPropsToState (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1095975)
    at new n (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1095345)
    at vo (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1347867)
    at Va (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1367357)
    at Ws (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1411048)
    at ku (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1397149)
    at Du (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1397077)
    at _u (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1396940)
    at gu (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1393906)
    at pu (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1391246)
ss @ 2.987ef8f6.chunk.js:2
n.callback @ 2.987ef8f6.chunk.js:2
po @ 2.987ef8f6.chunk.js:2
hs @ 2.987ef8f6.chunk.js:2
Ou @ 2.987ef8f6.chunk.js:2
t.unstable_runWithPriority @ 2.987ef8f6.chunk.js:2
Hi @ 2.987ef8f6.chunk.js:2
Au @ 2.987ef8f6.chunk.js:2
gu @ 2.987ef8f6.chunk.js:2
pu @ 2.987ef8f6.chunk.js:2
Yu @ 2.987ef8f6.chunk.js:2
(anonymous) @ 2.987ef8f6.chunk.js:2
yu @ 2.987ef8f6.chunk.js:2
rc @ 2.987ef8f6.chunk.js:2
t.render @ 2.987ef8f6.chunk.js:2
(anonymous) @ main.3bc2b167.chunk.js:1
(anonymous) @ main.3bc2b167.chunk.js:1
(anonymous) @ 2.987ef8f6.chunk.js:2
Promise.then (async)
(anonymous) @ 2.987ef8f6.chunk.js:2
577 @ main.3bc2b167.chunk.js:1
l @ index.html?Expires=1688581472&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8wMzNiYWQxYi1jOGUyLTRlZTUtYjhmOC1mNGMxOWMzM2NhMzcuY3RmY2xvdWQubmV0LzVXSWFWMFhtdHk0dG9tNzJyMDVRM1cvaW5kZXguaHRtbCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4ODU4MTQ3Mn19fV19&Signature=ZX1o~Lq8fKKeh4UMSaMLYxfoCnJPh6fU3rfr7Hv6eZGN23~J04IDTxWiJNyWNWSjixHV~L6N8alwZ77UvF7WuUWZr5eL36MOk95MnMHHu3S381xBCmOS9DrYEhER4cTOEXu0sdhoFJm6vQU4~3zkKCxY-dJOtDpgfCPpGFw8yG0T1MRSWx7isOOZvf~o~WLNO5sPGnD3FCBZidCFra2xCVmbyfVL7375FU6i3eA8PThLZSy5tr1FlokZUG35RJeuKalP4eMUvIpp~wcrirNEIlT~C4aXvNtZLfMP~wjDmDXx4ibRtMhsKOhftyS-M6L2FY~kbHwvbTqlor5pkZOuTw__&Key-Pair-Id=K1FL5TKJLAFZQZ:1
t @ index.html?Expires=1688581472&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8wMzNiYWQxYi1jOGUyLTRlZTUtYjhmOC1mNGMxOWMzM2NhMzcuY3RmY2xvdWQubmV0LzVXSWFWMFhtdHk0dG9tNzJyMDVRM1cvaW5kZXguaHRtbCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4ODU4MTQ3Mn19fV19&Signature=ZX1o~Lq8fKKeh4UMSaMLYxfoCnJPh6fU3rfr7Hv6eZGN23~J04IDTxWiJNyWNWSjixHV~L6N8alwZ77UvF7WuUWZr5eL36MOk95MnMHHu3S381xBCmOS9DrYEhER4cTOEXu0sdhoFJm6vQU4~3zkKCxY-dJOtDpgfCPpGFw8yG0T1MRSWx7isOOZvf~o~WLNO5sPGnD3FCBZidCFra2xCVmbyfVL7375FU6i3eA8PThLZSy5tr1FlokZUG35RJeuKalP4eMUvIpp~wcrirNEIlT~C4aXvNtZLfMP~wjDmDXx4ibRtMhsKOhftyS-M6L2FY~kbHwvbTqlor5pkZOuTw__&Key-Pair-Id=K1FL5TKJLAFZQZ:1
r @ index.html?Expires=1688581472&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8wMzNiYWQxYi1jOGUyLTRlZTUtYjhmOC1mNGMxOWMzM2NhMzcuY3RmY2xvdWQubmV0LzVXSWFWMFhtdHk0dG9tNzJyMDVRM1cvaW5kZXguaHRtbCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4ODU4MTQ3Mn19fV19&Signature=ZX1o~Lq8fKKeh4UMSaMLYxfoCnJPh6fU3rfr7Hv6eZGN23~J04IDTxWiJNyWNWSjixHV~L6N8alwZ77UvF7WuUWZr5eL36MOk95MnMHHu3S381xBCmOS9DrYEhER4cTOEXu0sdhoFJm6vQU4~3zkKCxY-dJOtDpgfCPpGFw8yG0T1MRSWx7isOOZvf~o~WLNO5sPGnD3FCBZidCFra2xCVmbyfVL7375FU6i3eA8PThLZSy5tr1FlokZUG35RJeuKalP4eMUvIpp~wcrirNEIlT~C4aXvNtZLfMP~wjDmDXx4ibRtMhsKOhftyS-M6L2FY~kbHwvbTqlor5pkZOuTw__&Key-Pair-Id=K1FL5TKJLAFZQZ:1
(anonymous) @ main.3bc2b167.chunk.js:1
2.987ef8f6.chunk.js:2 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at n.mapPropsToState (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1095975)
    at new n (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1095345)
    at vo (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1347867)
    at Va (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1367357)
    at Ws (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1411048)
    at ku (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1397149)
    at Du (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1397077)
    at _u (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1396940)
    at gu (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1393906)
    at pu (https://033bad1b-c8e2-4ee5-b8f8-f4c19c33ca37.ctfcloud.net/5WIaV0Xmty4tom72r05Q3W/static/js/2.987ef8f6.chunk.js:2:1391246)
```

**Comment by WillsB3** [comment]
Same here
